export const AG_GRID_LOCALE_ES_MX = {
  // Set Filter
  selectAll: "(Seleccionar todo)",
  selectAllSearchResults: "(Seleccionar todos los resultados de búsqueda)",
  addCurrentSelectionToFilter: "Agregar selección actual al filtro",
  searchOoo: "Buscar...",
  blanks: "(Vacíos)",
  noMatches: "No hay coincidencias",

  // Number Filter & Text Filter
  filterOoo: "Filtrar...",
  equals: "Igual a",
  notEqual: "No igual a",
  blank: "Vacío",
  notBlank: "No vacío",
  empty: "Elige uno",

  // Number Filter
  lessThan: "Menor que",
  greaterThan: "Mayor que",
  lessThanOrEqual: "Menor o igual a",
  greaterThanOrEqual: "Mayor o igual a",
  inRange: "Entre",
  inRangeStart: "Desde",
  inRangeEnd: "Hasta",

  // Text Filter
  contains: "Contiene",
  notContains: "No contiene",
  startsWith: "Comienza con",
  endsWith: "Termina con",

  // Date Filter
  dateFormatOoo: "aaaa-mm-dd",
  before: "Antes",
  after: "Después",

  // Filter Conditions
  andCondition: "Y",
  orCondition: "O",

  // Filter Buttons
  applyFilter: "Aplicar",
  resetFilter: "Reiniciar",
  clearFilter: "Limpiar",
  cancelFilter: "Cancelar",

  // Filter Titles
  textFilter: "Filtro de texto",
  numberFilter: "Filtro de número",
  dateFilter: "Filtro de fecha",
  setFilter: "Establecer filtro",

  // Group Column Filter
  groupFilterSelect: "Seleccionar campo:",

  // Advanced Filter
  advancedFilterContains: "contiene",
  advancedFilterNotContains: "no contiene",
  advancedFilterTextEquals: "igual a",
  advancedFilterTextNotEqual: "no igual a",
  advancedFilterStartsWith: "comienza con",
  advancedFilterEndsWith: "termina con",
  advancedFilterBlank: "está vacío",
  advancedFilterNotBlank: "no está vacío",
  advancedFilterEquals: "=",
  advancedFilterNotEqual: "!=",
  advancedFilterGreaterThan: ">",
  advancedFilterGreaterThanOrEqual: ">=",
  advancedFilterLessThan: "<",
  advancedFilterLessThanOrEqual: "<=",
  advancedFilterTrue: "es verdadero",
  advancedFilterFalse: "es falso",
  advancedFilterAnd: "Y",
  advancedFilterOr: "O",
  advancedFilterApply: "Aplicar",
  advancedFilterBuilder: "Constructor",
  advancedFilterValidationMissingColumn: "Falta columna",
  advancedFilterValidationMissingOption: "Falta opción",
  advancedFilterValidationMissingValue: "Falta valor",
  advancedFilterValidationInvalidColumn: "Columna no encontrada",
  advancedFilterValidationInvalidOption: "Opción no encontrada",
  advancedFilterValidationMissingQuote: "Falta una comilla final en el valor",
  advancedFilterValidationNotANumber: "El valor no es un número",
  advancedFilterValidationInvalidDate: "El valor no es una fecha válida",
  advancedFilterValidationMissingCondition: "Falta condición",
  advancedFilterValidationJoinOperatorMismatch:
    "Los operadores de unión dentro de una condición deben ser los mismos",
  advancedFilterValidationInvalidJoinOperator:
    "Operador de unión no encontrado",
  advancedFilterValidationMissingEndBracket: "Falta corchete de cierre",
  advancedFilterValidationExtraEndBracket: "Demasiados corchetes de cierre",
  advancedFilterValidationMessage:
    "La expresión tiene un error. ${variable} - ${variable}.",
  advancedFilterValidationMessageAtEnd:
    "La expresión tiene un error. ${variable} al final de la expresión.",
  advancedFilterBuilderTitle: "Filtro avanzado",
  advancedFilterBuilderApply: "Aplicar",
  advancedFilterBuilderCancel: "Cancelar",
  advancedFilterBuilderAddButtonTooltip: "Agregar filtro o grupo",
  advancedFilterBuilderRemoveButtonTooltip: "Eliminar",
  advancedFilterBuilderMoveUpButtonTooltip: "Mover arriba",
  advancedFilterBuilderMoveDownButtonTooltip: "Mover abajo",
  advancedFilterBuilderAddJoin: "Agregar grupo",
  advancedFilterBuilderAddCondition: "Agregar filtro",
  advancedFilterBuilderSelectColumn: "Seleccionar una columna",
  advancedFilterBuilderSelectOption: "Seleccionar una opción",
  advancedFilterBuilderEnterValue: "Ingresar un valor...",
  advancedFilterBuilderValidationAlreadyApplied:
    "El filtro actual ya está aplicado.",
  advancedFilterBuilderValidationIncomplete:
    "No todas las condiciones están completas.",
  advancedFilterBuilderValidationSelectColumn: "Debe seleccionar una columna.",
  advancedFilterBuilderValidationSelectOption: "Debe seleccionar una opción.",
  advancedFilterBuilderValidationEnterValue: "Debe ingresar un valor.",

  // Side Bar
  columns: "Columnas",
  filters: "Filtros",

  pivotMode: "Modo Pivote",
  groups: "Grupos de Filas",
  rowGroupColumnsEmptyMessage: "Arrastra aquí para establecer grupos de filas",
  values: "Valores",
  valueColumnsEmptyMessage: "Arrastra aquí para agregar",
  pivots: "Etiquetas de Columnas",
  pivotColumnsEmptyMessage:
    "Arrastra aquí para establecer etiquetas de columnas",

  // Header of the Default Group Column
  group: "Grupo",

  // Row Drag
  rowDragRow: "fila",
  rowDragRows: "filas",

  // Other
  loadingOoo: "Cargando...",
  loadingError: "ERR",
  noRowsToShow: "No hay filas para mostrar",
  enabled: "Habilitado",

  // Menu
  pinColumn: "Fijar Columna",
  pinLeft: "Fijar a la Izquierda",
  pinRight: "Fijar a la Derecha",
  noPin: "Sin Fijar",
  valueAggregation: "Agregación de Valores",
  noAggregation: "Ninguna",
  autosizeThiscolumn: "Autoajustar Esta Columna",
  autosizeAllColumns: "Autoajustar Todas las Columnas",
  groupBy: "Agrupar por",
  ungroupBy: "Desagrupar por",
  ungroupAll: "Desagrupar Todo",
  addToValues: "Agregar ${variable} a valores",
  removeFromValues: "Eliminar ${variable} de valores",
  addToLabels: "Agregar ${variable} a etiquetas",
  removeFromLabels: "Eliminar ${variable} de etiquetas",
  resetColumns: "Reiniciar Columnas",
  expandAll: "Expandir Todos los Grupos de Filas",
  collapseAll: "Cerrar Todos los Grupos de Filas",
  copy: "Copiar",
  ctrlC: "Ctrl+C",
  ctrlX: "Ctrl+X",
  copyWithHeaders: "Copiar con Encabezados",
  copyWithGroupHeaders: "Copiar con Encabezados de Grupo",
  cut: "Cortar",
  paste: "Pegar",
  ctrlV: "Ctrl+V",
  export: "Exportar",
  csvExport: "Exportar CSV",
  excelExport: "Exportar Excel",
  columnFilter: "Filtro de Columna",
  columnChooser: "Elegir Columnas",
  sortAscending: "Orden Ascendente",
  sortDescending: "Orden Descendente",
  sortUnSort: "Borrar Orden",

  // Enterprise Menu Aggregation and Status Bar
  sum: "Suma",
  first: "Primero",
  last: "Último",
  min: "Mínimo",
  max: "Máximo",
  none: "Ninguno",
  count: "Conteo",
  avg: "Promedio",
  filteredRows: "Filtradas",
  selectedRows: "Seleccionadas",
  totalRows: "Total de Filas",
  totalAndFilteredRows: "Filas",
  more: "Más",
  to: "a",
  of: "de",
  page: "Página",
  pageLastRowUnknown: "?",
  nextPage: "Página Siguiente",
  lastPage: "Última Página",
  firstPage: "Primera Página",
  previousPage: "Página Anterior",
  pageSizeSelectorLabel: "Tamaño de Página:",
  footerTotal: "Total",

  // Pivoting
  pivotColumnGroupTotals: "Total",

  pivotChartTitle: "Gráfica de Pivote",
  rangeChartTitle: "Gráfica de Rango",
  settings: "Gráfica",
  data: "Datos",
  format: "Formato",
  categories: "Categorías",
  defaultCategory: "(Ninguna)",
  series: "Series",
  switchCategorySeries: "Intercambiar Categoría / Series",
  categoryValues: "Valores de Categoría",
  seriesLabels: "Etiquetas de Series",
  aggregate: "Agregar",
  xyValues: "Valores X Y",
  paired: "Modo Pareado",
  axis: "Eje",
  xAxis: "Eje Horizontal",
  yAxis: "Eje Vertical",
  polarAxis: "Eje Polar",
  radiusAxis: "Eje de Radio",
  navigator: "Navegador",
  zoom: "Zoom",
  animation: "Animación",
  crosshair: "Mira",
  color: "Color",
  thickness: "Grosor",
  preferredLength: "Longitud Preferida",
  xType: "Tipo X",
  axisType: "Tipo de Eje",
  automatic: "Automático",
  category: "Categoría",
  number: "Número",
  time: "Tiempo",
  timeFormat: "Formato de Tiempo",
  autoRotate: "Rotar Automáticamente",
  labelRotation: "Rotación",
  circle: "Círculo",
  polygon: "Polígono",
  orientation: "Orientación",
  fixed: "Fijo",
  parallel: "Paralelo",
  perpendicular: "Perpendicular",
  radiusAxisPosition: "Posición",
  ticks: "Tics",
  gridLines: "Líneas de Cuadrícula",
  width: "Ancho",
  height: "Altura",
  length: "Longitud",
  padding: "Relleno",
  spacing: "Espaciado",
  chart: "Gráfica",
  title: "Título",
  titlePlaceholder: "Título de la gráfica - doble clic para editar",
  background: "Fondo",
  font: "Fuente",
  top: "Arriba",
  right: "Derecha",
  bottom: "Abajo",
  left: "Izquierda",
  labels: "Etiquetas",
  calloutLabels: "Etiquetas de Llamada",
  sectorLabels: "Etiquetas de Sector",
  positionRatio: "Relación de Posición",
  size: "Tamaño",
  shape: "Forma",
  minSize: "Tamaño Mínimo",
  maxSize: "Tamaño Máximo",
  legend: "Leyenda",
  position: "Posición",
  markerSize: "Tamaño del Marcador",
  markerStroke: "Trazo del Marcador",
  markerPadding: "Relleno del Marcador",
  itemSpacing: "Espaciado de Ítems",
  itemPaddingX: "Relleno de Ítems X",
  itemPaddingY: "Relleno de Ítems Y",
  layoutHorizontalSpacing: "Espaciado Horizontal",
  layoutVerticalSpacing: "Espaciado Vertical",
  strokeWidth: "Ancho del Trazo",
  offset: "Desplazamiento",
  offsets: "Desplazamientos",
  tooltips: "Tooltips",
  callout: "Llamada",
  markers: "Marcadores",
  shadow: "Sombra",
  blur: "Desenfoque",
  xOffset: "Desplazamiento X",
  yOffset: "Desplazamiento Y",
  lineWidth: "Ancho de Línea",
  lineDash: "Línea Discontinua",
  lineDashOffset: "Desplazamiento de Línea Discontinua",
  scrollingZoom: "Desplazamiento",
  scrollingStep: "Paso de Desplazamiento",
  selectingZoom: "Seleccionar",
  durationMillis: "Duración (ms)",
  crosshairLabel: "Etiqueta",
  crosshairSnap: "Ajustar al Nodo",
  normal: "Normal",
  bold: "Negrita",
  italic: "Cursiva",
  boldItalic: "Negrita Cursiva",
  predefined: "Predefinido",
  fillOpacity: "Opacidad de Relleno",
  strokeColor: "Color de Línea",
  strokeOpacity: "Opacidad de Línea",
  miniChart: "Mini-Gráfica",
  histogramBinCount: "Conteo de Bins",
  connectorLine: "Línea Conectora",
  seriesItems: "Ítems de Series",
  seriesItemType: "Tipo de Ítem",
  seriesItemPositive: "Positivo",
  seriesItemNegative: "Negativo",
  seriesItemLabels: "Etiquetas de Ítem",
  columnGroup: "Columna",
  barGroup: "Barra",
  pieGroup: "Pastel",
  lineGroup: "Línea",
  scatterGroup: "X Y (Dispersión)",
  areaGroup: "Área",
  polarGroup: "Polar",
  statisticalGroup: "Estadístico",
  hierarchicalGroup: "Jerárquico",
  specializedGroup: "Especializado",
  combinationGroup: "Combinación",
  groupedColumnTooltip: "Agrupado",
  stackedColumnTooltip: "Apilado",
  normalizedColumnTooltip: "100% Apilado",
  groupedBarTooltip: "Agrupado",
  stackedBarTooltip: "Apilado",
  normalizedBarTooltip: "100% Apilado",
  pieTooltip: "Pastel",
  donutTooltip: "Dona",
  lineTooltip: "Línea",
  groupedAreaTooltip: "Área",
  stackedAreaTooltip: "Apilado",
  normalizedAreaTooltip: "100% Apilado",
  scatterTooltip: "Dispersión",
  bubbleTooltip: "Burbuja",
  histogramTooltip: "Histograma",
  radialColumnTooltip: "Columna Radial",
  radialBarTooltip: "Barra Radial",
  radarLineTooltip: "Línea de Radar",
  radarAreaTooltip: "Área de Radar",
  nightingaleTooltip: "Nightingale",
  rangeBarTooltip: "Barra de Rango",
  rangeAreaTooltip: "Área de Rango",
  boxPlotTooltip: "Diagrama de Caja",
  treemapTooltip: "Mapa de Árbol",
  sunburstTooltip: "Sunburst",
  waterfallTooltip: "Cascada",
  heatmapTooltip: "Mapa de Calor",
  columnLineComboTooltip: "Columna y Línea",
  areaColumnComboTooltip: "Área y Columna",
  customComboTooltip: "Combinación Personalizada",
  innerRadius: "Radio Interno",
  startAngle: "Ángulo de Inicio",
  endAngle: "Ángulo Final",
  reverseDirection: "Invertir Dirección",
  groupPadding: "Relleno de Grupo",
  seriesPadding: "Relleno de Series",
  tile: "Mosaico",
  whisker: "Bigote",
  cap: "Tapa",
  capLengthRatio: "Relación de Longitud",
  labelPlacement: "Colocación de Etiquetas",
  inside: "Dentro",
  outside: "Fuera",
  noDataToChart: "No hay datos disponibles para graficar.",
  pivotChartRequiresPivotMode:
    "La Gráfica de Pivote requiere que el Modo Pivote esté habilitado.",
  chartSettingsToolbarTooltip: "Menú",
  chartLinkToolbarTooltip: "Vinculado a la Cuadrícula",
  chartUnlinkToolbarTooltip: "Desvinculado de la Cuadrícula",
  chartDownloadToolbarTooltip: "Descargar Gráfica",
  chartEdit: "Editar Gráfica",
  chartAdvancedSettings: "Configuraciones Avanzadas",
  chartLink: "Vincular a la Cuadrícula",
  chartUnlink: "Desvincular de la Cuadrícula",
  chartDownload: "Descargar Gráfica",
  seriesChartType: "Tipo de Gráfica de Series",
  seriesType: "Tipo de Series",
  secondaryAxis: "Eje Secundario",
  seriesAdd: "Agregar una serie",
  categoryAdd: "Agregar una categoría",
  advancedSettings: "Configuraciones Avanzadas",
  direction: "Dirección",
  horizontal: "Horizontal",
  vertical: "Vertical",
  seriesGroupType: "Tipo de Grupo",
  groupedSeriesGroupType: "Agrupado",
  stackedSeriesGroupType: "Apilado",
  normalizedSeriesGroupType: "100% Apilado",

  // ARIA
  ariaAdvancedFilterBuilderItem:
    "${variable}. Nivel ${variable}. Presiona ENTER para editar.",
  ariaAdvancedFilterBuilderItemValidation:
    "${variable}. Nivel ${variable}. ${variable} Presiona ENTER para editar.",
  ariaAdvancedFilterBuilderList: "Lista del Constructor de Filtro Avanzado",
  ariaAdvancedFilterBuilderFilterItem: "Condición de Filtro",
  ariaAdvancedFilterBuilderGroupItem: "Grupo de Filtro",
  ariaAdvancedFilterBuilderColumn: "Columna",
  ariaAdvancedFilterBuilderOption: "Opción",
  ariaAdvancedFilterBuilderValueP: "Valor",
  ariaAdvancedFilterBuilderJoinOperator: "Operador de Unión",
  ariaAdvancedFilterInput: "Entrada de Filtro Avanzado",
  ariaChecked: "marcado",
  ariaColumn: "Columna",
  ariaColumnGroup: "Grupo de Columnas",
  ariaColumnFiltered: "Columna Filtrada",
  ariaColumnSelectAll: "Alternar Selección de Todas las Columnas",
  ariaDateFilterInput: "Entrada de Filtro de Fecha",
  ariaDefaultListName: "Lista",
  ariaFilterColumnsInput: "Entrada de Filtro de Columnas",
  ariaFilterFromValue: "Filtrar desde valor",
  ariaFilterInput: "Entrada de Filtro",
  ariaFilterList: "Lista de Filtro",
  ariaFilterToValue: "Filtrar hasta valor",
  ariaFilterValue: "Valor del Filtro",
  ariaFilterMenuOpen: "Abrir Menú de Filtro",
  ariaFilteringOperator: "Operador de Filtrado",
  ariaHidden: "oculto",
  ariaIndeterminate: "indeterminado",
  ariaInputEditor: "Editor de Entrada",
  ariaMenuColumn: "Presiona ALT ABAJO para abrir el menú de columna",
  ariaFilterColumn: "Presiona CTRL ENTER para abrir el filtro",
  ariaRowDeselect: "Presiona SPACE para deseleccionar esta fila",
  ariaRowSelectAll: "Presiona SPACE para alternar selección de todas las filas",
  ariaRowToggleSelection: "Presiona SPACE para alternar selección de fila",
  ariaRowSelect: "Presiona SPACE para seleccionar esta fila",
  ariaRowSelectionDisabled:
    "La selección de filas está deshabilitada para esta fila",
  ariaSearch: "Buscar",
  ariaSortableColumn: "Presiona ENTER para ordenar",
  ariaToggleVisibility: "Presiona SPACE para alternar visibilidad",
  ariaToggleCellValue: "Presiona SPACE para alternar valor de celda",
  ariaUnchecked: "desmarcado",
  ariaVisible: "visible",
  ariaSearchFilterValues: "Buscar valores de filtro",
  ariaPageSizeSelectorLabel: "Tamaño de Página",
  ariaChartMenuClose: "Cerrar Menú de Edición de Gráfica",
  ariaSkeletonCellLoadingFailed: "La fila no se pudo cargar",
  ariaSkeletonCellLoading: "Cargando datos de la fila",

  // ARIA Labels for Drop Zones
  ariaRowGroupDropZonePanelLabel: "Grupos de Filas",
  ariaValuesDropZonePanelLabel: "Valores",
  ariaPivotDropZonePanelLabel: "Etiquetas de Columnas",
  ariaDropZoneColumnComponentDescription: "Presiona DELETE para eliminar",
  ariaDropZoneColumnValueItemDescription:
    "Presiona ENTER para cambiar el tipo de agregación",
  ariaDropZoneColumnGroupItemDescription: "Presiona ENTER para ordenar",
  // used for aggregate drop zone, format: {aggregation}{ariaDropZoneColumnComponentAggFuncSeparator}{column name}
  ariaDropZoneColumnComponentAggFuncSeparator: " de ",
  ariaDropZoneColumnComponentSortAscending: "ascendente",
  ariaDropZoneColumnComponentSortDescending: "descendente",

  // ARIA Labels for Dialogs
  ariaLabelColumnMenu: "Menú de Columna",
  ariaLabelColumnFilter: "Filtro de Columna",
  ariaLabelCellEditor: "Editor de Celda",
  ariaLabelDialog: "Diálogo",
  ariaLabelSelectField: "Seleccionar Campo",
  ariaLabelRichSelectField: "Campo de Selección Avanzada",
  ariaLabelTooltip: "Tooltip",
  ariaLabelContextMenu: "Menú Contextual",
  ariaLabelSubMenu: "Submenú",
  ariaLabelAggregationFunction: "Función de Agregación",
  ariaLabelAdvancedFilterAutocomplete: "Autocompletar Filtro Avanzado",
  ariaLabelAdvancedFilterBuilderAddField:
    "Agregar Campo al Constructor de Filtro Avanzado",
  ariaLabelAdvancedFilterBuilderColumnSelectField:
    "Seleccionar Campo de Columna en Constructor de Filtro Avanzado",
  ariaLabelAdvancedFilterBuilderOptionSelectField:
    "Seleccionar Campo de Opción en Constructor de Filtro Avanzado",
  ariaLabelAdvancedFilterBuilderJoinSelectField:
    "Seleccionar Operador de Unión en Constructor de Filtro Avanzado",

  // ARIA Labels for the Side Bar
  ariaColumnPanelList: "Lista de Columnas",
  ariaFilterPanelList: "Lista de Filtros",

  // Number Format (Status Bar, Pagination Panel)
  thousandSeparator: ",",
  decimalSeparator: ".",

  // Data types
  true: "Verdadero",
  false: "Falso",
  invalidDate: "Fecha Inválida",
  invalidNumber: "Número Inválido",
  january: "Enero",
  february: "Febrero",
  march: "Marzo",
  april: "Abril",
  may: "Mayo",
  june: "Junio",
  july: "Julio",
  august: "Agosto",
  september: "Septiembre",
  october: "Octubre",
  november: "Noviembre",
  december: "Diciembre",

  // Time formats
  timeFormatSlashesDDMMYYYY: "DD/MM/YYYY",
  timeFormatSlashesMMDDYYYY: "MM/DD/YYYY",
  timeFormatSlashesDDMMYY: "DD/MM/YY",
  timeFormatSlashesMMDDYY: "MM/DD/YY",
  timeFormatDotsDDMYY: "DD.M.YY",
  timeFormatDotsMDDYY: "M.DD.YY",
  timeFormatDashesYYYYMMDD: "YYYY-MM-DD",
  timeFormatSpacesDDMMMMYYYY: "DD MMMM YYYY",
  timeFormatHHMMSS: "HH:MM:SS",
  timeFormatHHMMSSAmPm: "HH:MM:SS AM/PM",
};
